// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb1JbteY6Zym6ujOQ0B1e2er4bWrZ8vIg',
    appId: '1:422089471520:web:5c39a4bd47b35d03c1ee45',
    messagingSenderId: '422089471520',
    projectId: 'londree-app-e8336',
    authDomain: 'londree-app-e8336.firebaseapp.com',
    storageBucket: 'londree-app-e8336.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjRqVcX-myFdlTt0EYJg3glJOP8O8D4mQ',
    appId: '1:422089471520:android:cb06c7d5f069698cc1ee45',
    messagingSenderId: '422089471520',
    projectId: 'londree-app-e8336',
    storageBucket: 'londree-app-e8336.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABj0NWa0AXo8XWB2imNQ3wBsjllFnUSn4',
    appId: '1:422089471520:ios:e33d0f24f6b3985fc1ee45',
    messagingSenderId: '422089471520',
    projectId: 'londree-app-e8336',
    storageBucket: 'londree-app-e8336.firebasestorage.app',
    androidClientId: '422089471520-s2o6a0jhisms35sa5534np3fqpiiafav.apps.googleusercontent.com',
    iosClientId: '422089471520-mso1h90o8dhuk87mqcnvi0e4j39qvi1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.londreeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABj0NWa0AXo8XWB2imNQ3wBsjllFnUSn4',
    appId: '1:422089471520:ios:e33d0f24f6b3985fc1ee45',
    messagingSenderId: '422089471520',
    projectId: 'londree-app-e8336',
    storageBucket: 'londree-app-e8336.firebasestorage.app',
    androidClientId: '422089471520-s2o6a0jhisms35sa5534np3fqpiiafav.apps.googleusercontent.com',
    iosClientId: '422089471520-mso1h90o8dhuk87mqcnvi0e4j39qvi1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.londreeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb1JbteY6Zym6ujOQ0B1e2er4bWrZ8vIg',
    appId: '1:422089471520:web:9087dd905969b850c1ee45',
    messagingSenderId: '422089471520',
    projectId: 'londree-app-e8336',
    authDomain: 'londree-app-e8336.firebaseapp.com',
    storageBucket: 'londree-app-e8336.firebasestorage.app',
  );
}
